//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 15/03/2016 16:57:32
namespace MonkeyTapWaveEngine
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/background.png </summary>
            public const string background_png = "Content/Assets/background.png";
            
            /// <summary> Path to Content/Assets/hit.wav </summary>
            public const string hit_wav = "Content/Assets/hit.wav";
            
            /// <summary> Path to Content/Assets/logo.png </summary>
            public const string logo_png = "Content/Assets/logo.png";
            
            /// <summary> Path to Content/Assets/monkey.png </summary>
            public const string monkey_png = "Content/Assets/monkey.png";
            
            /// <summary> Path to Content/Assets/title.mp3 </summary>
            public const string title_mp3 = "Content/Assets/title.mp3";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
